name: Daily CS2 Update Check

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Crawler
        run: python crawler.py
      - name: Commit updates
        run: |
          git config --global user.email "aloysiusfaustin@gmail.com"
          git config --global user.name "GitHub Action"
          git add data/cs2/updates_raw.json
          git diff --cached --quiet || git commit -m "Update CS2 data [bot]"
          git push
